packages:
  - .github/actions/*
  - docs
  - tests/*
  - packages/*
  - internal/*
  - scripts/*

enablePrePostScripts: true

engineStrict: true

allowBuilds:
  '@firebase/util': false
  '@swc/core': true
  esbuild: true
  nx: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
