packages:
  - .github/actions/*
  - docs
  - tests/*
  - packages/*

enablePrePostScripts: true

engineStrict: true

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - sharp
  - unrs-resolver
