export const MIGRATION_TRANSFORMS = {
  v2: {
    'list-cell-migration': 'List Cell Migration',
    'filled-variant-to-solid': 'Filled Variant to Solid',
    'typography-variant-cases': 'Typography Variant to kebab-case',
    'check-mark-migration': 'CheckMark Migration',
    'padding-to-vertical-padding': 'Padding to Vertical Padding',
    'padding-to-horizontal-padding': 'Padding to Horizontal Padding',
    'play-badge-migration': 'PlayBadge Migration',
    'heading-to-title': 'Heading to Title',
    'input-to-field': 'Input to Field',
    'modal-migration': 'ModalContainer Migration',
    'action-area-migration': 'ActionArea Migration',
    'icon-circle-close-migration': 'IconCircleClose Migration',
    'avatar-migration': 'Avatar Migration',
    'menu-bottom-migration': 'MenuBottom Migration',
    'leading-trailing-migration': 'Leading, Trailing Migration',
    'palette-to-atomic-semantic': 'Palette to Atomic & Semantic',
    'size-migration': 'Size Migration',
    'toast-migration': 'Toast Migration',
  },
  v3: {
    'typography-title1-to-display3': 'Typography Title1 to Display3',
    'empty-state-to-fallback-view': 'Empty State to Fallback View',
    'dialog-to-alert': 'Dialog to Alert',
    'stepper-migration': 'Progress Tracker to Stepper',
    'list-cell-active-to-selected': 'List Cell Active to Selected',
    'text-button-variant-to-color': 'TextButton Variant to Color',
    'button-secondary-migration': 'Button Secondary Migration',
    'pagination-migration': 'Pagination Migration',
    'compact-tooltip-migration': 'Compact Tooltip Migration',
    'section-message-show-to-open': 'Section Message Show to Open',
    'chip-naming-migration': 'Chip Naming Migration',
    'shadow-migration': 'Shadow Migration',
  },
};
