title: '[Question] '
labels: ['question']
body:
  - type: textarea
    attributes:
      label: Summary
      description: Provide a brief summary of your question.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: Provide additional details about your question.
    validations:
      required: true
