export const typographyVariants = [
  { name: 'display1', label: 'Display 1' },
  { name: 'display2', label: 'Display 2' },
  { name: 'display3', label: 'Display 3' },
  { name: 'title1', label: 'Title 1' },
  { name: 'title2', label: 'Title 2' },
  { name: 'title3', label: 'Title 3' },
  { name: 'heading1', label: 'Heading 1' },
  { name: 'heading2', label: 'Heading 2' },
  { name: 'headline1', label: 'Headline 1' },
  { name: 'headline2', label: 'Headline 2' },
  { name: 'body1', label: 'Body 1/Normal' },
  { name: 'body1-reading', label: 'Body 1/Reading' },
  { name: 'body2', label: 'Body 2/Normal' },
  { name: 'body2-reading', label: 'Body 2/Reading' },
  { name: 'label1', label: 'Label 1/Normal' },
  { name: 'label1-reading', label: 'Label 1/Reading' },
  { name: 'label2', label: 'Label 2' },
  { name: 'caption1', label: 'Caption 1' },
  { name: 'caption2', label: 'Caption 2' },
];
