name: JSX Tracking
description: Tracking JSX usage in other repositories

runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  gh_token:
    description: github token
    required: true
  webhook_url:
    description: slack webhook url
    required: true
