name: Generate Mobile Docs
description: Generate mobile docs from mobile document

runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  gh_token:
    description: github token
    required: true
