name: Code Connect Publish And Icon/Figma Sync
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'code connect push 여부'
        type: choice
        required: false
        default: 'true'
        options:
          - true
          - false

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node.js install
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@wanteddev'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.1.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store

      - name: Install dependencies
        run: pnpm install

      - uses: actions/cache@v4
        name: Nx cache
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nx-store-

      - name: Figma & Icon Sync
        run: pnpm run figma-icon-sync
        env:
          FIGMA_TOKEN: ${{ env.FIGMA_TOKEN }}

      - name: Build
        if: ${{ inputs.publish == 'true' }}
        run: pnpm run build

      - name: Publish
        if: ${{ inputs.publish == 'true' }}
        run: pnpm run publish:codeconnect --token ${{ env.FIGMA_TOKEN }} --skip-validation --batch-size 50

      - run: git config user.name "github-actions[bot]"
        if: always()
      - run: git config user.email "github-actions[bot]@users.noreply.github.com"
        if: always()

      - name: Create Branch And Commit
        if: always()
        run: |
          git branch feature/code-connect/${{ github.run_id }}
          git checkout feature/code-connect/${{ github.run_id }}
          git add .
          git commit -m "ci(wds,wds-icon): icon/figma sync and new code connect publish" --no-verify
          git push origin feature/code-connect/${{ github.run_id }}

      - name: Extract branch name
        if: always()
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Create New PR
        if: always()
        run: |
          gh pr create -B ${{ steps.extract_branch.outputs.branch }} -H feature/code-connect/${{ github.run_id }} --title "feat(wds,wds-icon): icon figma sync and new code connect publish" --body "icon figma sync and new code connect publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
