name: Component Tracking Report
on:
  schedule:
    - cron: 0 0 1 * *

jobs:
  tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/pnpm-install

      - name: Tracking And Report
        uses: ./.github/actions/jsx-tracking
        timeout-minutes: 15
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          webhook_url: ${{ secrets.MONITORING_WEBHOOK_URL }}
