name: Docs deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: 22.18.0

  AWS_REGION: ap-northeast-2
  AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUCKET: montage.wanted.co.kr

permissions:
  id-token: write
  contents: read

jobs:
  set-env:
    name: Set Env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set Environment Variable
        id: env-vars
        run: |
          server_type="www"

          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_OUTPUT
          echo "BUCKET=$BUCKET" >> $GITHUB_OUTPUT
          echo "SERVER_TYPE=$server_type" >> $GITHUB_OUTPUT

    outputs:
      node_version: ${{ steps.env-vars.outputs.NODE_VERSION }}
      aws_region: ${{ steps.env-vars.outputs.AWS_REGION }}
      bucket: ${{ steps.env-vars.outputs.BUCKET }}

      server_type: ${{ steps.env-vars.outputs.SERVER_TYPE }}

  set-pnpm:
    needs: [set-env]
    uses: wanteddev/github-actions-module/.github/workflows/pnpm.yml@main
    with:
      node_version: ${{ needs.set-env.outputs.node_version }}
    secrets: inherit

  build-react:
    needs: [set-env, set-pnpm]
    uses: wanteddev/github-actions-module/.github/workflows/build-react-v2.yml@main
    with:
      node_version: ${{ needs.set-env.outputs.node_version }}
      package_cache_key: ${{ needs.set-pnpm.outputs.pnpm_cache_key }}
      package_manager: pnpm
      build_cache_path: |
        .nx/cache
        docs/.next/cache
      build_cache_key: ${{ github.repository }}-${{ github.ref_name }}-${{ needs.set-env.outputs.server_type }}-build
      build_path: docs/out
      server_type: ${{ needs.set-env.outputs.server_type }}
      build_command: pnpm run build && pnpm -F docs build
    secrets: inherit

  push-s3:
    needs: [set-env, set-pnpm, build-react]
    uses: wanteddev/github-actions-module/.github/workflows/push-s3.yml@main
    with:
      aws_region: ${{ needs.set-env.outputs.aws_region }}
      server_type: ${{ needs.set-env.outputs.server_type }}
      build_path: docs/out
      build_cache_key: ${{ needs.build-react.outputs.build_cache_key }}
      run_command: |
        echo "build files to s3"
        aws s3 sync docs/out s3://${{ needs.set-env.outputs.bucket }}/ --delete
        aws cloudfront create-invalidation --distribution-id E43YG4RN0PRN4 --paths "/*"
    secrets: inherit

  # algolia:
  #   needs: [push-s3]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Push indices to Algolia
  #       id: algolia-crawler
  #       uses: algolia/algoliasearch-crawler-github-actions@v1.0.10
  #       with:
  #         crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
  #         crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
  #         algolia-app-id: ${{ secrets.APPLICATION_ID }}
  #         algolia-api-key: ${{ secrets.API_KEY }}
  #         site-url: https://montage.wanted.co.kr
  #         crawler-name: Montage Crawler
