name: Docs deploy
on:
  push:
    branches:
      - main
      - feature/sh031224/deploy-actions

env:
  PRETEXT: ""
  SERVICE: montage
  PLATFORM: front

  NODE_VERSION: 22.18.0

  AWS_REGION: ap-northeast-2
  AWS_DEPLOY_ROLE: ${{ secrets.AWS_DEPLOY_ROLE }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUCKET: montage.wanted.co.kr

permissions:
  id-token: write
  contents: read

jobs:
  set-env:
    name: Set Env
    runs-on: ubuntu-latest
    steps:
      - name: Set Common Env
        id: env
        run: |
          if [[ $PLATFORM == "front" ]]; then
            echo "::set-output name=SLACK_COLOR::00E5BA"
          else
            echo "::set-output name=SLACK_COLOR::003CFF"
          fi
          echo "::set-output name=PRETEXT::${PRETEXT}"
          echo "::set-output name=SERVICE::${SERVICE^^}"
          echo "::set-output name=SLACK_CHANNEL::#wds-deploy"
          echo "PLATFORM=${PLATFORM^^}" >> $GITHUB_OUTPUT
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_OUTPUT
          echo "BUCKET=$BUCKET" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set Environment Variable
        id: env-vars
        run: |
          server_type="www"
          build="prod"
          ref=${GITHUB_REF}

          IFS='/' read -ra vBranch <<< "$ref"
          branch=${vBranch[2]}

          IFS='/' read -ra vName <<< "$REPOSITORY"
          name=${vName[1]}

          echo "DATE=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          echo "SERVER_TYPE=$server_type" >> $GITHUB_OUTPUT
          echo "BUILD=$build" >> $GITHUB_OUTPUT
          echo "BRANCH=$branch" >> $GITHUB_OUTPUT
          echo "STAGE=www" >> $GITHUB_OUTPUT

          echo "HASH=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
          commit_message=$(git log -1 --pretty=format:%s | tr \" \')
          echo "COMMIT_MESSAGE=$commit_message" >> $GITHUB_OUTPUT

    outputs:
      slack_color: ${{ steps.env.outputs.SLACK_COLOR }}
      pretext: ${{ steps.env.outputs.PRETEXT }}
      service: ${{ steps.env.outputs.SERVICE }}
      slack_channel: ${{ steps.env.outputs.SLACK_CHANNEL }}
      stage: ${{ steps.env.outputs.STAGE }}
      platform: ${{ steps.env.outputs.PLATFORM }}

      node_version: ${{ steps.env.outputs.NODE_VERSION }}
      aws_region: ${{ steps.env.outputs.AWS_REGION }}
      bucket: ${{ steps.env.outputs.BUCKET }}

      date: ${{ steps.env-vars.outputs.DATE }}
      server_type: ${{ steps.env-vars.outputs.SERVER_TYPE }}
      build: ${{ steps.env-vars.outputs.BUILD }}
      barnch: ${{ steps.env-vars.outputs.BRANCH }}
      hash: ${{ steps.env-vars.outputs.HASH }}
      commit_msg: ${{ steps.env-vars.outputs.COMMIT_MESSAGE }}

  set-pnpm:
    needs: [set-env]
    uses: wanteddev/github-actions-module/.github/workflows/pnpm.yml@main
    with:
      node_version: ${{ needs.set-env.outputs.node_version }}
    secrets: inherit

  build-react:
    needs: [set-env, set-pnpm]
    uses: wanteddev/github-actions-module/.github/workflows/build-react-v2.yml@main
    with:
      node_version: ${{ needs.set-env.outputs.node_version }}
      package_cache_key: ${{ needs.set-pnpm.outputs.pnpm_cache_key }}
      package_manager: pnpm
      build_cache_path: |
        .nx/cache
        docs/.next/cache
      build_cache_key: ${{ github.repository }}-${{ github.ref_name }}-${{ needs.set-env.outputs.server_type }}-build
      build_path: docs/out
      server_type: ${{ needs.set-env.outputs.server_type }}
      build_command: pnpm run build && pnpm -F docs build
    secrets: inherit

  push-s3:
    needs: [set-env, set-pnpm, build-react]
    uses: wanteddev/github-actions-module/.github/workflows/push-s3.yml@main
    with:
      aws_region: ${{ needs.set-env.outputs.aws_region }}
      server_type: ${{ needs.set-env.outputs.server_type }}
      build_path: docs/out
      build_cache_key: ${{ needs.build-react.outputs.build_cache_key }}
      run_command: |
        echo "build files to s3"
        aws s3 sync docs/out s3://${{ needs.set-env.outputs.bucket }}/ --delete
        aws cloudfront create-invalidation --distribution-id E43YG4RN0PRN4 --paths "/*"
    secrets: inherit

  algolia:
    needs: [push-s3]
    runs-on: ubuntu-latest

    steps:
      - name: Push indices to Algolia
        id: algolia-crawler
        uses: algolia/algoliasearch-crawler-github-actions@v1.0.10
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.APPLICATION_ID }}
          algolia-api-key: ${{ secrets.API_KEY }}
          site-url: https://montage.wanted.co.kr
          crawler-name: Montage Crawler
