name: Docs deploy

on:
  workflow_dispatch:
    inputs:
      algolia:
        description: Run algolia crawler
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      server_type:
        description: Server type
        required: false
        default: "www"
        type: choice
        options:
          - "www"
          - "dev"

env:
  NODE_VERSION: 22.18.0
  AWS_REGION: ap-northeast-2
  BUCKET: montage.wanted.co.kr
  DEV_BUCKET: dev-montage.wanted.co.kr
  SERVER_TYPE: ${{ inputs.server_type }}

  CLOUDFRONT_DISTRIBUTION_ID: E43YG4RN0PRN4
  DEV_CLOUDFRONT_DISTRIBUTION_ID: E43YG4RN0PRN4

permissions:
  id-token: write
  contents: read

jobs:
  set-env:
    name: Set Env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set Environment Variable
        id: env-vars
        run: |
          SERVER_TYPE=$SERVER_TYPE

          if [ "$SERVER_TYPE" = "dev" ]; then
            BUCKET=$DEV_BUCKET
            CLOUDFRONT_DISTRIBUTION_ID=$DEV_CLOUDFRONT_DISTRIBUTION_ID
          else
            BUCKET=$BUCKET
            CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID
          fi

          echo "BUCKET=$BUCKET" >> $GITHUB_OUTPUT
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "AWS_REGION=$AWS_REGION" >> $GITHUB_OUTPUT
          echo "SERVER_TYPE=$SERVER_TYPE" >> $GITHUB_OUTPUT
          echo "CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID" >> $GITHUB_OUTPUT
    outputs:
      node_version: ${{ steps.env-vars.outputs.NODE_VERSION }}
      aws_region: ${{ steps.env-vars.outputs.AWS_REGION }}
      bucket: ${{ steps.env-vars.outputs.BUCKET }}
      cloudfront_distribution_id: ${{ steps.env-vars.outputs.CLOUDFRONT_DISTRIBUTION_ID }}
      server_type: ${{ steps.env-vars.outputs.SERVER_TYPE }}

  set-pnpm:
    needs: [set-env]
    uses: wanteddev/github-actions-module/.github/workflows/pnpm.yml@main
    with:
      node_version: ${{ needs.set-env.outputs.node_version }}
    secrets: inherit

  build-react:
    needs: [set-env, set-pnpm]
    uses: wanteddev/github-actions-module/.github/workflows/build-react-v2.yml@main
    with:
      node_version: ${{ needs.set-env.outputs.node_version }}
      package_cache_key: ${{ needs.set-pnpm.outputs.pnpm_cache_key }}
      package_manager: pnpm
      build_cache_path: |
        .nx/cache
        docs/.next/cache
      build_cache_key: ${{ github.repository }}-${{ github.ref_name }}-${{ needs.set-env.outputs.server_type }}-build
      build_path: docs/out
      server_type: ${{ needs.set-env.outputs.server_type }}
      build_command: pnpm run build && pnpm -F docs build
    secrets: inherit

  push-s3:
    needs: [set-env, set-pnpm, build-react]
    uses: wanteddev/github-actions-module/.github/workflows/push-s3.yml@main
    with:
      aws_region: ${{ needs.set-env.outputs.aws_region }}
      server_type: ${{ needs.set-env.outputs.server_type }}
      build_path: docs/out
      build_cache_key: ${{ needs.build-react.outputs.build_cache_key }}
      run_command: |
        echo "build files to s3"
        aws s3 sync docs/out s3://${{ needs.set-env.outputs.bucket }}/ --delete
        aws cloudfront create-invalidation --distribution-id ${{ needs.set-env.outputs.cloudfront_distribution_id }} --paths "/*"
    secrets: inherit

  algolia:
    needs: [push-s3]
    if: ${{ inputs.algolia == 'true' && inputs.server_type == 'www' }}
    runs-on: ubuntu-latest

    steps:
      - name: Push indices to Algolia
        id: algolia-crawler
        uses: algolia/algoliasearch-crawler-github-actions@v1.0.10
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.APPLICATION_ID }}
          algolia-api-key: ${{ secrets.API_KEY }}
          site-url: https://montage.wanted.co.kr
          crawler-name: Montage Crawler
