name: MCP Deploy
on:
  workflow_dispatch:
    inputs:
      server_type:
        description: 'Server type'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'www'
          - 'dev'
  workflow_call:
    inputs:
      server_type:
        description: Server type
        required: false
        default: 'dev'
        type: string

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  AWS_REGION: ap-northeast-2

  SERVICE: 'montage-mcp'

permissions:
  id-token: write
  contents: read

jobs:
  set-env:
    name: Set Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set Environment Variable
        id: env-vars
        run: |
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_OUTPUT
          echo "SERVER_TYPE=${{ inputs.server_type }}" >> $GITHUB_OUTPUT
          echo "ECR_REPOSITORY=$SERVICE/${{ inputs.server_type }}" >> $GITHUB_OUTPUT
          echo "TASK_DEFINITION=$SERVICE-${{ inputs.server_type }}" >> $GITHUB_OUTPUT
          echo "ECS_SERVICE=$SERVICE-${{ inputs.server_type }}-service" >> $GITHUB_OUTPUT
          echo "ECS_CLUSTER=montage-${{ inputs.server_type }}-cluster" >> $GITHUB_OUTPUT
    outputs:
      server_type: ${{ steps.env-vars.outputs.SERVER_TYPE }}
      short_sha: ${{ steps.env-vars.outputs.SHORT_SHA }}
      ecr_repository: ${{ steps.env-vars.outputs.ECR_REPOSITORY }}
      task_definition: ${{ steps.env-vars.outputs.TASK_DEFINITION }}
      ecs_service: ${{ steps.env-vars.outputs.ECS_SERVICE }}
      ecs_cluster: ${{ steps.env-vars.outputs.ECS_CLUSTER }}

  deploy:
    needs: [set-env]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Build wds-mcp
        run: pnpm lerna run build --scope @wanteddev/wds-mcp --include-dependencies
        env:
          MCP_TRACK_CLIENT_ID: ${{ secrets.MCP_TRACK_CLIENT_ID }}

      - name: Deploy standalone wds-mcp
        run: pnpm deploy --filter @wanteddev/wds-mcp --prod standalone --legacy

      - name: Configure AWS credentials DEV
        if: ${{ startsWith(needs.set-env.outputs.server_type, 'dev') }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials
        if: ${{ !startsWith(needs.set-env.outputs.server_type, 'dev') }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Mcp docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ needs.set-env.outputs.ecr_repository }}
          IMAGE_TAG: ${{ needs.set-env.outputs.short_sha }}
        run: |
          DOCKER_BUILDKIT=1 docker build \
          --platform=linux/amd64 \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
          -f Dockerfile \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-ecs:
    needs: [set-env, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials DEV
        if: ${{ startsWith(needs.set-env.outputs.server_type, 'dev') }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials
        if: ${{ !startsWith(needs.set-env.outputs.server_type, 'dev') }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        env:
          TASK_DEFINITION: ${{ needs.set-env.outputs.task_definition }}
        run: |
          aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query taskDefinition > task-definition.json

      - name: Deploy Amazon ECS task definition
        id: ecs-deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        timeout-minutes: 10
        with:
          task-definition: task-definition.json
          service: ${{ needs.set-env.outputs.ecs_service }}
          cluster: ${{ needs.set-env.outputs.ecs_cluster }}
          wait-for-service-stability: true
