name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false && github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js install
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@wanteddev"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10.13.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store

      - name: Install dependencies
        run: pnpm install

      - uses: actions/cache@v4
        name: Nx cache
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nx-store-

      - name: Build local packages
        run: pnpm run build

      - name: Run Test
        run: pnpm run test --silent --no-cache

      - name: Run ESLint Test
        run: pnpm run test:eslint

  send_slack:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'DO NOT ALERT') }}
    name: Send Slack Notification
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Parse Title
        id: parse-title
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data } = await github.rest.pulls.get({
              pull_number: context.issue.number,
              owner: 'wanteddev',
              repo: 'wds',
            });

            const title = data.title.replace(/\\/g, '\\\\').
              replace(/\u0008/g, '\\b').
              replace(/\t/g, '\\t').
              replace(/\n/g, '\\n').
              replace(/\f/g, '\\f').
              replace(/\r/g, '\\r').
              replace(/'/g, '\\\'').
              replace(/"/g, '\\"').
              replace(/`/g, '\\`');

            core.setOutput('title', title);
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                fields: [
                  {
                    title: 'PR 제목',
                    value: '[${{ github.event.repository.name }}] ${{ steps.parse-title.outputs.title }}',
                    short: false
                  },
                  {
                    title: '작성자',
                    value: '${{ github.event.pull_request.user.login }} (c.c <!subteam^S084RSQ5JJW>)',
                    short: false
                  }
                ],
                title: '>>> 리뷰하러 가기 >>>',
                title_link: '${{ github.event.pull_request.html_url }}',
                thumb_url: '${{ github.event.pull_request.user.avatar_url }}',
                footer: '리뷰 및 승인 부탁드립니다',
                footer_icon: 'https://wanted-dev.static.wanted.co.kr/images/icons/star_fill.svg'
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
